/*
 * File: app/view/AboutWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.AboutWindow', {
    extend: 'Ext.window.Window',

    height: 248,
    width: 501,
    layout: {
        type: 'absolute'
    },
    title: 'About',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'button',
                    x: 150,
                    y: 140,
                    height: 50,
                    width: 180,
                    text: 'OK'
                },
                {
                    xtype: 'label',
                    x: 10,
                    y: 10,
                    height: 190,
                    html: '<h1>NimrodIDE</h1><br>author: Yaskhan Ashimbayev<br>2013',
                    style: 'text-align: center;',
                    width: 450,
                    text: ''
                }
            ]
        });

        me.callParent(arguments);
    }

});