/*
 * File: app/view/ConfigWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.ConfigWindow', {
    extend: 'Ext.window.Window',

    height: 692,
    width: 962,
    layout: {
        type: 'border'
    },
    title: 'My Window',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            width: 914,
                            title: 'Tab 1'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    region: 'south',
                    height: 49,
                    layout: {
                        type: 'absolute'
                    },
                    items: [
                        {
                            xtype: 'button',
                            x: 820,
                            y: 10,
                            height: 30,
                            width: 120,
                            text: 'MyButton'
                        },
                        {
                            xtype: 'button',
                            x: 690,
                            y: 10,
                            height: 30,
                            width: 120,
                            text: 'MyButton'
                        }
                    ]
                },
                {
                    xtype: 'treepanel',
                    region: 'west',
                    width: 300,
                    title: 'My Tree Panel',
                    viewConfig: {

                    },
                    dockedItems: [
                        {
                            xtype: 'textfield',
                            dock: 'left',
                            width: 100
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});