/*
 * File: app/view/MainViewport.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainViewport', {
    extend: 'Ext.container.Viewport',

    requires: [
        'MyApp.view.MainToolbar',
        'MyApp.view.MainFilesPanel',
        'MyApp.view.MainVariablesPanel',
        'MyApp.view.MainConsolePanel',
        'MyApp.view.MainSourceTabPanel'
    ],

    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'maintoolbar',
                    region: 'north'
                },
                {
                    xtype: 'MainFilesPanelAlias',
                    region: 'west',
                    split: true
                },
                {
                    xtype: 'MainVariablesPanelAlias',
                    region: 'east',
                    split: true,
                    title: 'Outline'
                },
                {
                    xtype: 'MainConsolePanelAlias',
                    region: 'south',
                    split: true
                },
                {
                    xtype: 'MainSourceTabPanelAlias',
                    region: 'center'
                }
            ]
        });

        me.callParent(arguments);
    }

});