/*
 * File: app/view/MainFilesPanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainFilesPanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.MainFilesPanelAlias',

    height: 444,
    width: 228,
    layout: {
        type: 'border'
    },
    bodyBorder: false,
    collapsible: true,
    title: 'Files',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            height: 113,
                            layout: {
                                type: 'border'
                            },
                            title: 'App Exploler',
                            items: [
                                {
                                    xtype: 'treepanel',
                                    region: 'center',
                                    header: false,
                                    title: 'My Tree Panel',
                                    viewConfig: {

                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'textfield',
                                            dock: 'top',
                                            padding: '2 2 2 2',
                                            width: 100
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'border'
                            },
                            title: 'Project Exploler',
                            dockedItems: [
                                {
                                    xtype: 'textfield',
                                    dock: 'top',
                                    padding: '2 2 2 2'
                                }
                            ],
                            items: [
                                {
                                    xtype: 'treepanel',
                                    region: 'center',
                                    header: false,
                                    title: 'My Tree Panel',
                                    viewConfig: {

                                    }
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});