/*
 * File: app/view/MainConsolePanel.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MainConsolePanel', {
    extend: 'Ext.panel.Panel',
    alias: 'widget.MainConsolePanelAlias',

    height: 150,
    layout: {
        type: 'accordion'
    },
    collapsed: false,
    collapsible: true,
    title: 'Console',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    frameHeader: false,
                    headerPosition: 'bottom',
                    overlapHeader: false,
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            title: 'Tab 1'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 2'
                        },
                        {
                            xtype: 'panel',
                            title: 'Tab 3'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});