/*
 * File: app/view/SearchWindow.js
 *
 * This file was generated by Sencha Architect version 2.2.2.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.SearchWindow', {
    extend: 'Ext.window.Window',

    requires: [
        'MyApp.view.Search.searcheComboBox',
        'MyApp.view.Search.ModeFieldset'
    ],

    height: 345,
    width: 683,
    layout: {
        type: 'border'
    },
    title: 'Searche',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    region: 'center',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Find',
                            items: [
                                {
                                    xtype: 'mycombobox10',
                                    x: 20,
                                    y: 10
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 50,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 130,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 90,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'searchfieldset',
                                    x: 10,
                                    y: 40
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 280,
                                    y: 40,
                                    height: 130,
                                    width: 260,
                                    title: 'Direction',
                                    items: [
                                        {
                                            xtype: 'checkboxgroup',
                                            height: 100,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Up'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Down'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 20,
                                    y: 180,
                                    boxLabel: 'Match whole words only'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 20,
                                    y: 240,
                                    boxLabel: 'Wrap around'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 20,
                                    y: 210,
                                    boxLabel: 'Match case'
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                closable: false
                            }
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'Relace',
                            items: [
                                {
                                    xtype: 'mycombobox10',
                                    x: 20,
                                    y: 10
                                },
                                {
                                    xtype: 'searchfieldset',
                                    x: 10,
                                    y: 70
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 40,
                                    width: 640,
                                    fieldLabel: 'Replace'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 80,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 120,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 280,
                                    y: 70,
                                    height: 130,
                                    width: 90,
                                    title: 'Direction',
                                    items: [
                                        {
                                            xtype: 'checkboxgroup',
                                            height: 100,
                                            layout: {
                                                align: 'stretch',
                                                type: 'vbox'
                                            },
                                            items: [
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Up'
                                                },
                                                {
                                                    xtype: 'checkboxfield',
                                                    boxLabel: 'Down'
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 140,
                                    y: 210,
                                    boxLabel: 'Match whole words only'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 20,
                                    y: 240,
                                    boxLabel: 'Wrap around'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 20,
                                    y: 210,
                                    boxLabel: 'Match case'
                                },
                                {
                                    xtype: 'fieldset',
                                    x: 520,
                                    y: 160,
                                    height: 80,
                                    width: 140,
                                    layout: {
                                        type: 'absolute'
                                    },
                                    title: '',
                                    items: [
                                        {
                                            xtype: 'checkboxfield',
                                            x: 0,
                                            y: 50,
                                            boxLabel: 'In selection'
                                        },
                                        {
                                            xtype: 'button',
                                            x: -2,
                                            y: 10,
                                            height: 30,
                                            width: 120,
                                            text: 'Replace all'
                                        }
                                    ]
                                }
                            ],
                            tabConfig: {
                                xtype: 'tab',
                                closable: false
                            }
                        },
                        {
                            xtype: 'panel',
                            layout: {
                                type: 'absolute'
                            },
                            title: 'In files',
                            tabConfig: {
                                xtype: 'tab',
                                closable: false
                            },
                            items: [
                                {
                                    xtype: 'mycombobox10',
                                    x: 20,
                                    y: 10
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 40,
                                    width: 640,
                                    fieldLabel: 'Replace'
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 70,
                                    width: 640,
                                    fieldLabel: 'Filter'
                                },
                                {
                                    xtype: 'combobox',
                                    x: 20,
                                    y: 100,
                                    width: 600,
                                    fieldLabel: 'Directory'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 230,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'button',
                                    x: 630,
                                    y: 100,
                                    height: 20,
                                    width: 30,
                                    text: '..'
                                },
                                {
                                    xtype: 'button',
                                    x: 550,
                                    y: 190,
                                    height: 30,
                                    width: 110,
                                    text: 'MyButton'
                                },
                                {
                                    xtype: 'searchfieldset',
                                    x: 20,
                                    y: 130
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 290,
                                    y: 230,
                                    boxLabel: 'Match whole words only'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 450,
                                    y: 140,
                                    boxLabel: 'Match case'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 290,
                                    y: 200,
                                    boxLabel: 'In hidder folders'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 290,
                                    y: 170,
                                    boxLabel: 'In all sub folder'
                                },
                                {
                                    xtype: 'checkboxfield',
                                    x: 290,
                                    y: 140,
                                    boxLabel: 'Follow current doc.'
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});